# Site settings
title: Abbas Arezoo - Designer and Developer
email: abbas@abbasarezoo.co.uk
description: Hello there, I'm Abbas. I design and build websites and applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.abbasarezoo.com" # the base hostname & protocol for your site
twitter_username: DesignSheffield
github_username:  abbasarezoo

# Build settings
markdown: kramdown
syntax_highlighter: rouge

# Ingored files
exclude:
  - config.rb
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - node_modules
  - CNAME
  - package.json
  - _css-src
  - _js-src
  - _img-src
  - aajekyll.sublime-project
  - aajekyll.sublime-workspace
  - form-info.txt
