# Site settings
title: Abbas Arezoo - Web Design & Front-end Development
email: abbas@abbasarezoo.co.uk
description: I'm a designer and developer based in Sheffield, UK. I work with a huge range of clients from local start-ups to established global brands. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.abbasarezoo.com" # the base hostname & protocol for your site
twitter_username: DesignSheffield
github_username:  abbasarezoo

# Build settings
markdown: kramdown
syntax_highlighter: rouge

# Ingored files
exclude:
  - config.rb
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - node_modules
  - CNAME
  - package.json
  - _css-src
  - _js-src
  - _img-src
  - aa.sublime-project
  - aa.sublime-workspace
  - form-info.txt
